ALTER TABLE Prisoner
  ALTER COLUMN prision_id SET DATA TYPE TEXT;

ALTER TABLE Prisoner
  ALTER COLUMN prisoner_id SET DATA TYPE NUMERIC,
  ALTER COLUMN visitor_1 SET DATA TYPE NUMERIC,
  ALTER COLUMN visitor_2 SET DATA TYPE NUMERIC,